export enum ErrorCode {
  // Auth
  EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'AUTH_USERNAME_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  ALREADY_VERIFIED = 'AUTH_ALREADY_VERIFIED',
  INVALID_OTP = 'AUTH_INVALID_OTP',
  OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // User
  USER_AVATAR_NOT_FOUND = 'USER_AVATAR_NOT_FOUND',
  USER_BACKGROUND_NOT_FOUND = 'USER_BACKGROUND_NOT_FOUND',
  INVALID_FILE_TYPE = 'USER_INVALID_FILE_TYPE',

  // Friendship
  FRIENDSHIP_SELF_REQUEST = 'FRIENDSHIP_SELF_REQUEST',
  FRIENDSHIP_TARGET_NOT_FOUND = 'FRIENDSHIP_TARGET_NOT_FOUND',
  FRIENDSHIP_ALREADY_EXISTS = 'FRIENDSHIP_ALREADY_EXISTS',
  FRIENDSHIP_BLOCKED = 'FRIENDSHIP_BLOCKED',
  FRIENDSHIP_NOT_FOUND = 'FRIENDSHIP_NOT_FOUND',
  FRIENDSHIP_NOT_PENDING = 'FRIENDSHIP_NOT_PENDING',
  FRIENDSHIP_NOT_ACCEPTED = 'FRIENDSHIP_NOT_ACCEPTED',
  FRIENDSHIP_NOT_BLOCKED = 'FRIENDSHIP_NOT_BLOCKED',

  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
